name: CI

on: [push, pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        
    - name: Install dependencies
      run: |
        poetry install

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Use the same Ruby version as before
        bundler-cache: true # This will run 'bundle install' and cache installed gems automatically

    - name: Install hiptest-publisher
      run: gem install hiptest-publisher

    - name: List files and display config file
      run: |
        ls -l
        cat hiptest-publisher.conf   

    - name: Regenerate tests
      run: hiptest-publisher --config-file hiptest-publisher.conf --test-run-id 912056 --without=actionwords

    - name: Run tests
      run: poetry run pytest